
source 'https://rubygems.org'

gem 'rails', '3.2.16'

gem 'rest-client' # for rest-graph
gem 'rest-graph', :path => '../../'

group :test do
  gem 'muack'
  gem 'webmock'
end

platforms :ruby do
  gem 'yajl-ruby'
end

platforms :jruby do
  gem 'jruby-openssl'
end

platforms :rbx do
  gem 'rubysl-fiber'      # used in rest-core
  gem 'rubysl-singleton'  # used in rake
  gem 'rubysl-rexml'      # used in crack used in webmock
  gem 'rubysl-bigdecimal' # used in crack used in webmock
  gem 'rubysl-test-unit'  # used in activesupport
  gem 'rubysl-enumerator' # used in activesupport
  gem 'rubysl-benchmark'  # used in activesupport
  gem 'racc'              # used in journey used in actionpack
end
