
source 'http://rubygems.org'

gem 'rails', '3.2.15'

gem 'rest-client' # for rest-graph
gem 'yajl-ruby'   # for rest-graph
gem 'rest-graph', :path => '../../'

group(:test) do
  gem 'muack'
  gem 'webmock'
end

platform(:rbx) do
  gem 'rubysl-enumerator' # required by activesupport
  gem 'rubysl-rexml'      # required by webmock required by crack
  gem 'racc'              # required by journey required by actionpack
end
