
source 'http://rubygems.org'

gem 'rails', '2.3.15'

gem 'rest-client' # for rest-graph
gem 'yajl-ruby'   # for rest-graph
gem 'rest-graph', :path => '../../'

group 'test' do
  gem 'muack'
  gem 'webmock'
end
